CXX = g++
CXXFLAGS = -Wall -g

lab11a: lab11a.cpp
	$(CXX) $(CXXFLAGS) lab11a.cpp -o lab11a

lab11b: lab11b.cpp
	$(CXX) $(CXXFLAGS) lab11b.cpp -o lab11b

run1:
	./lab11a

run2:
	./lab11b

val1:
	valgrind ./lab11a

val2:
	valgrind ./lab11b
